# hw1:温度数据分析
## 某城市一周的最高气温(℃)为:[20, 30, 29, 31, 32, 30, 29]
### -计算平均气温最高气温最低气温
### -找出气温超过30℃的天数

In [2]:
import numpy as np

In [3]:
temps = np.array([20, 30, 29, 31, 32, 30, 29])
print('平均气温:', "%.3f" %np.mean(temps))
print('最高气温:', np.max(temps))
print('最低气温:', np.min(temps))
print('气温超30℃的天数:', len(temps[temps>30]))
print('气温超30℃的天数:') 
print(np.cumsum(np.where(temps>30, 1, 0))[-1])
print(np.count_nonzero(temps>30))

平均气温: 28.714
最高气温: 32
最低气温: 20
气温超30℃的天数: 2
气温超30℃的天数:
2
2


# hw2:学生成绩统计
## 5名学生成绩[85, 90, 78, 92, 88]
### -计算平均分中位数标准差
### -将成绩转换为十分制

In [4]:
score = np.array([85, 90, 78, 92, 88])
print(np.sort(score))

[78 85 88 90 92]


In [5]:
print('平均分:', np.mean(score))
print('中位数:', np.median(score))
print('标准差:', "%.3f" %np.std(score))
print(score/10)

平均分: 86.6
中位数: 88.0
标准差: 4.883
[8.5 9.  7.8 9.2 8.8]


# hw3:矩阵运算
## A = [[1, 2], [3, 4]]    B = [[5, 6], [7, 8]]
### -计算A+B,A*B(逐个元素乘法)
### -计算A与B的矩阵乘法

In [6]:

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('A+B:', A+B, sep = '\n')
print('A*B:', A*B, sep = '\n')
print('矩阵乘法结果:', A@B, sep = '\n')

A+B:
[[ 6  8]
 [10 12]]
A*B:
[[ 5 12]
 [21 32]]
矩阵乘法结果:
[[19 22]
 [43 50]]


# hw4:随机数据生成
## 生成一个(3, 4)的随机整数数组，范围[0, 10)
### -计算每列的最大值与每行的最小值
### -将数组中的所有奇数替换为-1

In [ ]:
np.random.seed(0)
arr = np.random.randint(0, 10, (3, 4))
print(arr)
for i in range (3):
    print("第%d行的最小值:"%(i+1), np.min(arr[i,:]))
for i in range (4):
    print("第%d列的最大值:" %(i+1), np.max(arr[:,i]))
print('每列的最大值:', np.max(arr, axis = 0)) # axis = 0 :列
print('每行的最小值:', np.min(arr, axis = 1)) # axis = 1 :行
print(np.where(arr%2, -1, arr))
arr[arr%2 == 1] = -1
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
第1行的最小值: 0
第2行的最小值: 3
第3行的最小值: 2
第1列的最大值: 7
第2列的最大值: 9
第3列的最大值: 7
第4列的最大值: 6
每列的最大值: [7 9 7 6]
每行的最小值: [0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


# hw5:数组变形
## 创建1-12的一维数组，转换为(3,4)的二维数组
### -计算每行的和与每列的平均值
### -将数组展回一维数组

In [29]:
arr = np.arange(1,13)
print(arr)
arr = np.reshape(arr, (3, 4))
print(arr)
print('每行的和:', np.sum(arr, axis = 1))
print('每列的平均值:', np.mean(arr, axis = 0))
arr = np.reshape(arr, (12))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和: [10 26 42]
每列的平均值: [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# hw6:统计函数应用
## 某公司6个月的销售额(万元)[120, 135, 110, 125, 130, 140]
### -计算销售额总和,均值,方差
### -找出销售额最高的月份和最低的月份

In [33]:
sale = np.array([120,135, 110, 125, 130, 140])
print('总和:', np.sum(sale))
print('平均值:', np.mean(sale))
print('方差:', np.var(sale))
print('销售额最高月:', np.argmax(sale) + 1)
print('销售额最低月:', np.argmin(sale) + 1)

总和: 760
平均值: 126.66666666666667
方差: 97.22222222222223
销售额最高月: 6
销售额最低月: 3


# hw7:拼接数组
## A = [1, 2, 3]; B = [4, 5, 6]
### -将A,B水平拼接
### -将A,B垂直拼接

In [36]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.concatenate([A, B])
D = np.reshape(C, (2, 3))
print('水平拼接:', C)
print('垂直拼接:', D)

水平拼接: [1 2 3 4 5 6]
垂直拼接: [[1 2 3]
 [4 5 6]]


# hw8:唯一值与排序
## 给定数组[2, 1, 2, 3, 1, 4, 3]
### -找出唯一值并排序
### -计算每个唯一值出现次数

In [41]:
arr = np.array([2, 1, 2, 3, 1, 4, 3])
unique_arr, counts = np.unique(arr, return_counts =True)
print(unique_arr, counts, sep = '\n')

[1 2 3 4]
[2 2 2 1]
