# 一、ndarray(数组对象保存与处理)
## 1.ndarray的特性
### 多维性

多维性(类似于列表),同质性,高效性 
支持多维数组;所有元素类型统一通过dtype指定;基于连续内存储存,支持向量化运算

In [1]:
import numpy as np

In [2]:
arr = np.array(5) # 0维ndarray
print(arr)
print('arr的维度:', arr.ndim) # number of dimensions

5
arr的维度: 0


In [3]:
arr = np.array([1, 2, 3, 4, 5]) # sep = ' '
print(arr)
print('arr的维度:', arr.ndim)

[1 2 3 4 5]
arr的维度: 1


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # two-dimensional
print(arr)
print('arr的维度:', arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr的维度: 2


### 同质性

In [5]:
arr = np.array([1, 'hello', 3]) # 1 here is transformed into a string ('1')!!!
print(arr)

['1' 'hello' '3']


In [6]:
arr = np.array([1, 2.5]) # 1 here is transformed into a float ('1.')!!!
print(arr)

[1.  2.5]


## 2.ndarray的属性
shape:数组的行数和列数 

ndim:维度

size:总元素个数 

dtype:数组元素类型 

T:转置 

itemsize:单个元素占用的内存字节数 

nbytes:数组内存总占用量(size * itemsize) 

flags:内存存储方式(是否连续)

In [7]:
arr = np.array(1)
print('arr:', arr)
print('shape:',arr.shape)
print('ndim:', arr.ndim)
print('size:', arr.size)
print('dtype:', arr.dtype)
print('T:', arr.T)
print('itemsize:', arr.itemsize)

arr: 1
shape: ()
ndim: 0
size: 1
dtype: int64
T: 1
itemsize: 8


In [8]:
arr = np.array([1, 2, 3, 4])
print('arr:', arr)
print('shape:',arr.shape)
print('ndim:', arr.ndim)
print('size:', arr.size)
print('dtype:', arr.dtype)
print('T:', arr.T)
print('itemsize:', arr.itemsize)

arr: [1 2 3 4]
shape: (4,)
ndim: 1
size: 4
dtype: int64
T: [1 2 3 4]
itemsize: 8


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('arr:', arr)
print('shape:',arr.shape)  # So two-dimensional ndarray is actually a matrix!!!
print('ndim:', arr.ndim)
print('size:', arr.size)
print('dtype:', arr.dtype)
print('T:', arr.T)
print('itemsize:', arr.itemsize)

arr: [[1 2 3]
 [4 5 6]]
shape: (2, 3)
ndim: 2
size: 6
dtype: int64
T: [[1 4]
 [2 5]
 [3 6]]
itemsize: 8


In [10]:
arr = np.array([['a', 'b', 'c'], ['d', 'e', 'f']])
print('arr:', arr)
print('shape:',arr.shape)
print('ndim:', arr.ndim)
print('size:', arr.size)
print('dtype:', arr.dtype)
print('T:', arr.T)
print('itemsize:', arr.itemsize)

arr: [['a' 'b' 'c']
 ['d' 'e' 'f']]
shape: (2, 3)
ndim: 2
size: 6
dtype: <U1
T: [['a' 'd']
 ['b' 'e']
 ['c' 'f']]
itemsize: 4


In [11]:
arr = np.array([1, 2.5]) # 1 here is transformed into a float ('1.')!!!
print('arr:', arr)
print('shape:',arr.shape)
print('ndim:', arr.ndim)
print('size:', arr.size)
print('dtype:', arr.dtype)
print('T:', arr.T)
print('itemsize:', arr.itemsize)

arr: [1.  2.5]
shape: (2,)
ndim: 1
size: 2
dtype: float64
T: [1.  2.5]
itemsize: 8


## 3.ndarray的创建方式
基础构造:手动 np.array();np.copy()

预定义形状填充:用于快速初始化固定形状数组 np.zeros();np.ones();np.empty();np.full()

基于数值范围生成:生成如时间序列的数值序列 np.arange();np.linspace();np.logspace()

特殊矩阵生成:数学运算专用 np.eye();np.diag()

随机数组生成:模拟实验数据、初始化神经网络权重等 np.random.rand();np.random.radn();np.random.randint()

高级构造方法:处理非结构化数据(文件、字符串等)或通过函数生成复杂数组 np.array();np.loadtxt();np.fromfunction()

In [12]:
# 基础方法
list1 = [4, 5, 6]
arr = np.array( list1, dtype = np.float64 ) # list is the parameter
print(arr.ndim) #属性不需要()
print(arr)

1
[4. 5. 6.]


In [13]:
# copy
arr1 = np.copy(arr) # 元素上arr1与arr相同,但并不是同一个数组
print(arr1)
arr1[0] = 8
print(arr1, arr, sep = '  ')

[4. 5. 6.]
[8. 5. 6.]  [4. 5. 6.]


In [14]:
# 预定义形状填充
arr0 = np.zeros((2, 3)) # float64
arr1 = np.ones((5, 8), dtype = int) # float64
arr2 = np.empty((2, 3))
arr3 = np.full((3, 3), fill_value = 'a') # This needs two paraments: shape & fill_value
print(arr0, arr1, arr2, arr3, sep = '\n')

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.24610994e-306 1.42413555e-306 1.78019082e-306]]
[['a' 'a' 'a']
 ['a' 'a' 'a']
 ['a' 'a' 'a']]


In [15]:
# imitate the shape of 'arr'
arr4 = np.zeros_like(arr)
print(arr4)
arr4 = np.empty_like(arr)
print(arr4)
arr4 = np.ones_like(arr)
print(arr4)
arr4 = np.full_like(arr, 2026)
print(arr4)

[0. 0. 0.]
[0. 0. 0.]
[1. 1. 1.]
[2026. 2026. 2026.]


In [16]:
# 等差数列
arr = np.arange(2,11,2) # np.arange(start, end, step): the end is not included!!!
print(arr)

[ 2  4  6  8 10]


In [17]:
# 等间隔数列
arr = np.linspace(0, 100, 5, dtype = int) # np.linspace(start, end, number of the nums): the end can be included!!!
print(arr)
arr = np.arange(0, 101, 25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [18]:
# 对数间隔序列(指数幂)
arr = np.logspace(0, 4, 3, base = 2) 
# np.logspace(min_of_exponential, max_of_exponential, number of nums(exponentials), base = ?)
print(arr)

[ 1.  4. 16.]


## 矩阵
0维:标量
1维:向量
2维:矩阵
3维及以上:张量

零矩阵:所有元素为0

单位矩阵:主对角线上为1,其余为0

对角矩阵:只有主对角线上有非零值

对称矩阵:A = A的转置

In [19]:
# 特殊矩阵
# 单位矩阵
arr = np.eye(3, 4, dtype = int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [20]:
# 对角矩阵
arr = np.diag([1, 2, 3]) # 按顺序自左上角填入
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [21]:
# 随机数组生成
# 生成0至1的随机浮点数(均匀分布)
arr = np.random.rand(2, 3) # np.random.rand(shape) 
print(arr)

[[0.95346564 0.39682526 0.05649156]
 [0.99423034 0.08152336 0.55250334]]


In [22]:
# 生成指定范围区间的随机浮点数(均匀分布)
arr = np.random.uniform(3, 6, (2, 3)) # np.random.uniform(min, max, shape)
print(arr)

[[5.88953724 4.78704403 4.89918129]
 [5.09987977 3.80050153 4.45577535]]


In [23]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 30, (2, 3)) # np.random.randint(min, max, shape)
print(arr)

[[19 12 10]
 [19 29  6]]


In [24]:
# 生成随机数列(正态分布)
arr = np.random.randn(2, 3) # np.random.randn(shape)
print(arr)

[[-0.28583909  0.64008925 -1.17170964]
 [-0.3936281  -2.19547797 -0.23825281]]


In [25]:
# 设置随机种子
np.random.seed(20) # This do not return an array!!!
# seed determine the random array!!!
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


## 4.ndarray的数据类型
bool

int8/uint8……int64/uint64: 8位……64位

float16/32/64:半精度,单精度,双精度

complex64/128

In [26]:
arr = np.array([1, 0, 2, 0], dtype = np.bool)
# arr = np.array([1, 0, 2, 0], dtype = 'bool')
print(arr)

[ True False  True False]


In [27]:
arr = np.array([1, 0, 128, 0], dtype = 'int')
print(arr)

[  1   0 128   0]


## 5.索引与切片
基本索引

行/列切片

连续切片

使用slice函数

bool索引

In [28]:
# 一维数组
arr = np.random.randint(1, 100, 20)
print(arr[0]) # index starts from zero!!! 
print(arr[:]) # 获取全部
print(arr[2:5]) # 依旧不包括end
print(arr[4:1:-1]) # 依旧逆序
print(arr[(arr>10) & (arr<35)]) # bool索引
print(arr[slice(2, 5, 2)]) # step

17
[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]
[17  8 99]
[99  8 17]
[17 17 27 14 26 33]
[17 99]


In [29]:
# 二维数组
arr = np.random.randint(1, 100, (4, 8))
print(arr)
print(arr[1, 3]) # all indexs start from zero!!!
print(arr[ 1 , 2:5 ]) # ,分割行与列, :代表全部
print(arr[arr > 40]) # output is a one-dimensional array!!!
print(arr[2][arr[2]>50]) # bool index in a row
print(arr[:,2][arr[:,2]>60]) # bool index in a line

[[11  7 76 19  4 78 18 44]
 [17 19 80 91 60 72 76 30]
 [46  7 64 79 25 19 94 34]
 [79 43 95  4 19 71 53 23]]
91
[80 91 60]
[76 78 44 80 91 60 72 76 46 64 79 94 79 43 95 71 53]
[64 79 94]
[76 80 64 95]


## 6.ndarray的运算



In [30]:
# 算术运算
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
# It is different from list/tuple/string!!!
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
print(a1 ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [31]:
# 二维
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
# 对应位置进行运算,并不是做矩阵运算
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
print(a1 ** 2)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [32]:
# 广播机制:数组一定条件下可以扩展,自动补完来进行运算
# 条件: shape上,行或列有相同或为1
a1 = np.array([1, 2, 3])
a2 = np.array([[4],[5],[6]])
print(a1 + a2)
'''
a1:
1 2 3
1 2 3
1 2 3 
a2:
4 4 4
5 5 5
6 6 6
'''

[[5 6 7]
 [6 7 8]
 [7 8 9]]


'\na1:\n1 2 3\n1 2 3\n1 2 3 \na2:\n4 4 4\n5 5 5\n6 6 6\n'

In [33]:
# 矩阵运算
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
# 矩阵乘法:@; 加减非特殊
print(a1 @ a2)
print(a2 @ a1)


[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]
[[ 66  81  96]
 [102 126 150]
 [ 30  36  42]]


# 二、numpy常用函数
## 1.基本数学函数

In [34]:
# sqrt: return a float
print(np.sqrt(9))
print(np.sqrt([1, 4, 9, 16]))
arr = np.array([1, 25, 81])
print(np.sqrt(arr))

3.0
[1. 2. 3. 4.]
[1. 5. 9.]


In [35]:
# 计算指数
print(np.exp(1)) # return e **(num)

2.718281828459045


In [36]:
# 计算对数
print(np.log(2.718281828459045))
print(np.log10(10))

1.0
1.0


In [37]:
# 计算三角函数
print(np.sin(np.pi / 2))
print(np.cos(np.pi))

1.0
-1.0


In [38]:
# 计算绝对值
arr = np.array([1, -2, 3, -4, 0])
print(np.abs(arr))

[1 2 3 4 0]


In [39]:
# 计算a ** b
print(np.power(arr, 3))

[  1  -8  27 -64   0]


In [40]:
# 四舍五入 (5:奇数入,偶数舍)
print(np.round([4.3, 9.6, 3.3, 5.5, 4.5]))
# 4.5 is rounded into 4

[ 4. 10.  3.  6.  4.]


In [41]:
# 向上/向下取整
arr = np.array([1.6, 25.5, 80.2])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 81.]
[ 1. 25. 80.]


In [42]:
# 检测缺失值(NaN)
np.isnan([1, 2, 3, np.nan])

array([False, False, False,  True])

## 2.基本统计函数

In [43]:
arr = np.random.randint(1, 20, 8)
print(arr)

[15  5 12  9  7 16 19 15]


In [44]:
# 求和
print(np.sum([1, 2, 3]))

6


In [45]:
# 平均值
print(np.mean([1, 2, 3, 4, 6]))

3.2


In [46]:
# 中位数
print(np.median([5, 4, 2, 1, 6, 6]))
print(np.median([1, 2, 3, 4, 6]))

4.5
3.0


In [47]:
# 计算标准差与方差
# 方差
print(np.var([1, 2, 3]))
print(np.var([1, 1, 1, 1, 1, 1, 1, 100]))
# 标准差
print(np.std([1, 2, 3]))

0.6666666666666666
1071.984375
0.816496580927726


In [48]:
# 计算最值
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))
# np.argmax(); np.argmin():给出对应的index

[15  5 12  9  7 16 19 15]
19 6
5 1


In [49]:
# 分位数
# 中位数是特殊的分位数
print(arr)
print(np.percentile(arr, 20)) 
# 分位数 = (num - 1) * percent * (arr[i + 1] - arr[i]) + arr[i]
# 6.2 = 7*0.2*(5 - 2) + 2

[15  5 12  9  7 16 19 15]
7.800000000000001


In [50]:
# 累积和,累积乘
arr = np.array([1, 2, 3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

6
[1 3 6]
[1 2 6]


## 3.比较函数

In [51]:
# 是否大于/小于/等于(逐个判断)
print(np.greater([3, 4, 5, 6, 7, 8], 4))
print(np.less([3, 4, 5, 6, 7, 8], 4))
print(np.equal([3, 4, 5, 6, 7, 8], 4))
# 数组之间比较
print(np.equal([3, 4, 5], [4, 3, 5]))

[False False  True  True  True  True]
[ True False False False False False]
[False  True False False False False]
[False False  True]


In [52]:
# 逻辑运算
print(np.logical_and([1, 0], [1, 1]))
print(np.logical_or([1, 0], [1, 1]))
print(np.logical_not([1, 0]))

[ True False]
[ True  True]
[False  True]


In [53]:
# 检查是否存在/任意元素为True
print(np.any([0, 0, 0, 0, 0]))
print(np.all([1, 1, 1, 1, 1]))

False
True


In [54]:
# 自定义条件
# print(np.where(条件,符合条件的取值,不符合条件的取值))
# np.where(a,b,c): a?b:c

arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr>3, arr, 0))
print(np.where(arr<3, 1, 0))

score = np.random.randint(40, 100, 10)
print(score)
print(np.where(score >= 60, '及格', '不及格'))
print(np.where(score>=60, np.where(score>=80, '优秀', '良好') ,'不及格')) # 嵌套使用多个分类

# np.select(条件,返回结果)
print(np.select([score>=90, score>=80, (score>=60) & (score<80), score<60],
                ['优秀', '良好', '及格', '不及格'],
                default = '未知'))

[0 0 0 4 5]
[1 1 0 0 0]
[91 50 82 73 61 90 57 80 58 82]
['及格' '不及格' '及格' '及格' '及格' '及格' '不及格' '及格' '不及格' '及格']
['优秀' '不及格' '优秀' '良好' '良好' '优秀' '不及格' '优秀' '不及格' '优秀']
['优秀' '不及格' '良好' '及格' '及格' '优秀' '不及格' '良好' '不及格' '良好']


## 4.排序函数

In [55]:
np.random.seed(0)
arr = np.random.randint(1, 100, 10)
print(arr)

# A way which will not change the original array!!!
print(np.sort(arr))
print(arr)
# This returns the indexs after sorting
print(np.argsort(arr))

# This will change the original array!!!
print(arr.sort()) # The function returns None
print(arr)
# This is actually meaningless!!!
print(np.argsort(arr))

[45 48 65 68 68 10 84 22 37 88]
[10 22 37 45 48 65 68 68 84 88]
[45 48 65 68 68 10 84 22 37 88]
[5 7 8 0 1 2 3 4 6 9]
None
[10 22 37 45 48 65 68 68 84 88]
[0 1 2 3 4 5 6 7 8 9]


In [56]:
# 去重函数
# sort and unique
print(np.unique(arr))

[10 22 37 45 48 65 68 84 88]


In [57]:
# 数组拼接
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate( (arr1, arr2) ))
# 数组切割
print(np.split(arr, 5)) # In this way, the array must be splited evenly or the program crashes!!!
print(np.split(arr, [1, 3, 5, 7, 9])) # List the indexs

[1 2 3 4 5 6]
[array([10, 22], dtype=int32), array([37, 45], dtype=int32), array([48, 65], dtype=int32), array([68, 68], dtype=int32), array([84, 88], dtype=int32)]
[array([10], dtype=int32), array([22, 37], dtype=int32), array([45, 48], dtype=int32), array([65, 68], dtype=int32), array([68, 84], dtype=int32), array([88], dtype=int32)]


In [58]:
# 调整数组shape
print(np.reshape(arr, [2, 5])) ## The size of array must be appropriate or the program crashes!!!

[[10 22 37 45 48]
 [65 68 68 84 88]]
